2019-02-21 00:03:46,050 ERROR: Exception on /edit_profile [POST] [in c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\engine\base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\engine\default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\routes.py", line 96, in edit_profile
    db.session.commit()
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\session.py", line 1023, in commit
    self.transaction.commit()
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\session.py", line 487, in commit
    self._prepare_impl()
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\session.py", line 466, in _prepare_impl
    self.session.flush()
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\session.py", line 2436, in flush
    self._flush(objects)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\session.py", line 2574, in _flush
    transaction.rollback(_capture_exception=True)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\util\langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\util\compat.py", line 277, in reraise
    raise value
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\session.py", line 2534, in _flush
    flush_context.execute()
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 416, in execute
    rec.execute(self)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 583, in execute
    uow,
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\persistence.py", line 236, in save_obj
    update,
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\orm\persistence.py", line 976, in _emit_update_statements
    statement, multiparams
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\engine\base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\sql\elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\engine\base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\engine\base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\engine\base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\util\compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\util\compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\engine\base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\veshi\desktop\projects\site_moneta\flask\lib\site-packages\sqlalchemy\engine\default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username [SQL: 'UPDATE user SET username=?, about_me=? WHERE user.id = ?'] [parameters: ('vova', 'I am supercool! ', 2)] (Background on this error at: http://sqlalche.me/e/gkpj)
2019-02-21 23:30:14,578 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-21 23:39:21,500 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-21 23:40:12,223 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-21 23:41:38,909 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:15:44,501 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:18:23,036 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:25:15,812 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:26:36,642 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:27:14,711 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:27:41,670 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:28:16,693 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:33:12,572 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-23 23:34:12,825 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 01:56:59,047 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 01:58:07,562 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 01:59:09,149 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 02:00:02,743 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 02:00:48,180 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 02:02:16,361 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 02:04:19,639 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 02:05:03,821 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 02:05:42,785 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 02:09:06,008 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 14:54:54,984 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:43]
2019-02-24 15:15:11,889 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:46]
2019-02-24 15:17:16,725 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:46]
2019-02-24 15:17:54,165 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:46]
2019-02-24 15:22:39,546 INFO: Microblog startup [in C:\Users\veshi\Desktop\Projects\Site_Moneta\moneta\app\__init__.py:46]
